
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es' | 'it' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    'header.title': 'Wordless',
    'header.subtitle': 'Challenge your mind with word puzzles',
    'header.letsPlay': "Let's Play!",
    'header.learnMore': 'Learn More',
    'game.confirmChange': 'Are you sure you want to change the word length? This will reset your current game.',
    'game.wordLengthUpdated': 'Word length updated to {{length}} letters',
    'game.newWordGenerated': 'A new word has been generated',
    'game.congratulations': 'Congratulations!',
    'game.solved': 'You solved the puzzle!',
    'game.gameOver': 'Game Over',
    'game.wordWas': 'The word was: {{word}}',
    'game.wordTooShort': 'Word too short',
    'game.enterWord': 'Please enter a {{length}}-letter word',
    'game.confirmReset': 'Are you sure you want to reset the game?',
    'game.loading': 'Loading new puzzle...',
    'game.dailyChallenge': 'Daily Word Challenge',
    'game.newPuzzle': 'A new puzzle every day!',
    'game.youWon': 'You Won!',
    'game.betterLuck': 'Better Luck Next Time!',
    'game.solvedIn': 'You solved it in {{count}} guesses!',
    'game.tryDifferent': 'Try a different word length for a new challenge.',
    'game.playAgain': 'Play Again',
    'game.try': 'Try {{length}} Letters',
    'about.title': 'About Wordless',
    'about.description1': 'Wordless is a challenging word puzzle game that tests your vocabulary and deduction skills.',
    'about.description2': 'Each day brings a new puzzle with words of varying lengths from 3 to 8 letters.',
    'about.description3': 'Use the color-coded feedback to narrow down the correct word within 6 attempts.',
    'about.description4': 'Challenge yourself with different word lengths and improve your word-solving abilities!',
    'howToPlay.title': 'How to Play',
    'howToPlay.gameRules': 'Game Rules',
    'howToPlay.rule1': 'Guess the hidden word in 6 attempts or less',
    'howToPlay.rule2': 'Each guess must be a valid word of the correct length',
    'howToPlay.rule3': 'After each guess, the tile colors will change to show how close your guess was',
    'howToPlay.rule4': 'Use the feedback to make better guesses',
    'howToPlay.tileColors': 'Tile Colors',
    'howToPlay.green': 'Letter is in the word and in the correct position',
    'howToPlay.yellow': 'Letter is in the word but in the wrong position',
    'howToPlay.gray': 'Letter is not in the word',
    'howToPlay.tips': 'Pro Tips',
    'howToPlay.tip1.title': 'Start with Common Letters',
    'howToPlay.tip1.desc': 'Begin with words containing common vowels and consonants like A, E, I, O, U, R, S, T, L, N.',
    'howToPlay.tip2.title': 'Use Process of Elimination',
    'howToPlay.tip2.desc': 'Pay attention to gray letters - they are not in the word. Avoid using them in future guesses.',
    'howToPlay.tip3.title': 'Position Matters',
    'howToPlay.tip3.desc': 'Yellow letters are in the word but wrong position. Try them in different spots.',
    'howToPlay.tip4.title': 'Think Strategically',
    'howToPlay.tip4.desc': 'Each guess should give you maximum information about letter positions and presence.',
    'howToPlay.what': 'What is Wordless?',
    'howToPlay.whatDesc1': 'Wordless is inspired by the popular word puzzle game format but offers unique features like variable word lengths and daily challenges.',
    'howToPlay.whatDesc2': 'Perfect for word game enthusiasts who want to challenge themselves with puzzles of different difficulty levels.',
    'howToPlay.faq': 'Frequently Asked Questions',
    'howToPlay.faq1.q': 'Can I play previous puzzles?',
    'howToPlay.faq1.a': 'Each day features a unique puzzle. You can change word lengths to get different challenges.',
    'howToPlay.faq2.q': 'What word lengths are available?',
    'howToPlay.faq2.a': 'You can play with words from 3 to 8 letters long, each offering different difficulty levels.',
    'howToPlay.faq3.q': 'Are there hints available?',
    'howToPlay.faq3.a': 'The game provides color-coded feedback after each guess - this is your hint system!',
    'howToPlay.faq4.q': 'Can I play offline?',
    'howToPlay.faq4.a': 'Yes! Once loaded, you can play the current puzzle without an internet connection.',
  },
  fr: {
    'header.title': 'Wordless',
    'header.subtitle': 'Défiez votre esprit avec des énigmes de mots',
    'header.letsPlay': 'Jouons !',
    'header.learnMore': 'En Savoir Plus',
    'game.confirmChange': 'Êtes-vous sûr de vouloir changer la longueur du mot ? Cela réinitialisera votre jeu actuel.',
    'game.wordLengthUpdated': 'Longueur du mot mise à jour à {{length}} lettres',
    'game.newWordGenerated': 'Un nouveau mot a été généré',
    'game.congratulations': 'Félicitations !',
    'game.solved': 'Vous avez résolu l\'énigme !',
    'game.gameOver': 'Jeu Terminé',
    'game.wordWas': 'Le mot était : {{word}}',
    'game.wordTooShort': 'Mot trop court',
    'game.enterWord': 'Veuillez entrer un mot de {{length}} lettres',
    'game.confirmReset': 'Êtes-vous sûr de vouloir réinitialiser le jeu ?',
    'game.loading': 'Chargement d\'une nouvelle énigme...',
    'game.dailyChallenge': 'Défi Quotidien de Mots',
    'game.newPuzzle': 'Une nouvelle énigme chaque jour !',
    'game.youWon': 'Vous avez Gagné !',
    'game.betterLuck': 'Bonne Chance la Prochaine Fois !',
    'game.solvedIn': 'Vous l\'avez résolu en {{count}} tentatives !',
    'game.tryDifferent': 'Essayez une longueur de mot différente pour un nouveau défi.',
    'game.playAgain': 'Rejouer',
    'game.try': 'Essayer {{length}} Lettres',
    'about.title': 'À Propos de Wordless',
    'about.description1': 'Wordless est un jeu d\'énigmes de mots stimulant qui teste votre vocabulaire et vos compétences de déduction.',
    'about.description2': 'Chaque jour apporte une nouvelle énigme avec des mots de longueurs variables de 3 à 8 lettres.',
    'about.description3': 'Utilisez les commentaires codés par couleur pour réduire le mot correct en 6 tentatives.',
    'about.description4': 'Défiez-vous avec différentes longueurs de mots et améliorez vos capacités de résolution de mots !',
    'howToPlay.title': 'Comment Jouer',
    'howToPlay.gameRules': 'Règles du Jeu',
    'howToPlay.rule1': 'Devinez le mot caché en 6 tentatives ou moins',
    'howToPlay.rule2': 'Chaque supposition doit être un mot valide de la bonne longueur',
    'howToPlay.rule3': 'Après chaque supposition, les couleurs des tuiles changeront pour montrer à quel point votre supposition était proche',
    'howToPlay.rule4': 'Utilisez les commentaires pour faire de meilleures suppositions',
    'howToPlay.tileColors': 'Couleurs des Tuiles',
    'howToPlay.green': 'La lettre est dans le mot et à la bonne position',
    'howToPlay.yellow': 'La lettre est dans le mot mais à la mauvaise position',
    'howToPlay.gray': 'La lettre n\'est pas dans le mot',
    'howToPlay.tips': 'Conseils de Pro',
    'howToPlay.tip1.title': 'Commencez par les Lettres Communes',
    'howToPlay.tip1.desc': 'Commencez par des mots contenant des voyelles et consonnes communes comme A, E, I, O, U, R, S, T, L, N.',
    'howToPlay.tip2.title': 'Utilisez l\'Élimination',
    'howToPlay.tip2.desc': 'Faites attention aux lettres grises - elles ne sont pas dans le mot. Évitez de les utiliser dans les suppositions futures.',
    'howToPlay.tip3.title': 'La Position Compte',
    'howToPlay.tip3.desc': 'Les lettres jaunes sont dans le mot mais à la mauvaise position. Essayez-les à différents endroits.',
    'howToPlay.tip4.title': 'Pensez Stratégiquement',
    'howToPlay.tip4.desc': 'Chaque supposition devrait vous donner un maximum d\'informations sur les positions et la présence des lettres.',
    'howToPlay.what': 'Qu\'est-ce que Wordless ?',
    'howToPlay.whatDesc1': 'Wordless s\'inspire du format de jeu d\'énigmes de mots populaire mais offre des fonctionnalités uniques comme des longueurs de mots variables et des défis quotidiens.',
    'howToPlay.whatDesc2': 'Parfait pour les amateurs de jeux de mots qui veulent se défier avec des énigmes de différents niveaux de difficulté.',
    'howToPlay.faq': 'Questions Fréquemment Posées',
    'howToPlay.faq1.q': 'Puis-je jouer les énigmes précédentes ?',
    'howToPlay.faq1.a': 'Chaque jour présente une énigme unique. Vous pouvez changer les longueurs de mots pour obtenir différents défis.',
    'howToPlay.faq2.q': 'Quelles longueurs de mots sont disponibles ?',
    'howToPlay.faq2.a': 'Vous pouvez jouer avec des mots de 3 à 8 lettres, chacun offrant différents niveaux de difficulté.',
    'howToPlay.faq3.q': 'Y a-t-il des indices disponibles ?',
    'howToPlay.faq3.a': 'Le jeu fournit des commentaires codés par couleur après chaque supposition - c\'est votre système d\'indices !',
    'howToPlay.faq4.q': 'Puis-je jouer hors ligne ?',
    'howToPlay.faq4.a': 'Oui ! Une fois chargé, vous pouvez jouer l\'énigme actuelle sans connexion internet.',
  },
  es: {
    'header.title': 'Wordless',
    'header.subtitle': 'Desafía tu mente con rompecabezas de palabras',
    'header.letsPlay': '¡Juguemos!',
    'header.learnMore': 'Saber Más',
    'game.confirmChange': '¿Estás seguro de que quieres cambiar la longitud de la palabra? Esto reiniciará tu juego actual.',
    'game.wordLengthUpdated': 'Longitud de palabra actualizada a {{length}} letras',
    'game.newWordGenerated': 'Se ha generado una nueva palabra',
    'game.congratulations': '¡Felicidades!',
    'game.solved': '¡Has resuelto el rompecabezas!',
    'game.gameOver': 'Juego Terminado',
    'game.wordWas': 'La palabra era: {{word}}',
    'game.wordTooShort': 'Palabra demasiado corta',
    'game.enterWord': 'Por favor ingresa una palabra de {{length}} letras',
    'game.confirmReset': '¿Estás seguro de que quieres reiniciar el juego?',
    'game.loading': 'Cargando nuevo rompecabezas...',
    'game.dailyChallenge': 'Desafío Diario de Palabras',
    'game.newPuzzle': '¡Un nuevo rompecabezas cada día!',
    'game.youWon': '¡Ganaste!',
    'game.betterLuck': '¡Mejor Suerte la Próxima Vez!',
    'game.solvedIn': '¡Lo resolviste en {{count}} intentos!',
    'game.tryDifferent': 'Prueba una longitud de palabra diferente para un nuevo desafío.',
    'game.playAgain': 'Jugar Otra Vez',
    'game.try': 'Probar {{length}} Letras',
    'about.title': 'Acerca de Wordless',
    'about.description1': 'Wordless es un desafiante juego de rompecabezas de palabras que pone a prueba tu vocabulario y habilidades de deducción.',
    'about.description2': 'Cada día trae un nuevo rompecabezas con palabras de longitudes variables de 3 a 8 letras.',
    'about.description3': 'Usa la retroalimentación codificada por colores para reducir la palabra correcta en 6 intentos.',
    'about.description4': '¡Desafíate con diferentes longitudes de palabras y mejora tus habilidades para resolver palabras!',
    'howToPlay.title': 'Cómo Jugar',
    'howToPlay.gameRules': 'Reglas del Juego',
    'howToPlay.rule1': 'Adivina la palabra oculta en 6 intentos o menos',
    'howToPlay.rule2': 'Cada suposición debe ser una palabra válida de la longitud correcta',
    'howToPlay.rule3': 'Después de cada suposición, los colores de las fichas cambiarán para mostrar qué tan cerca estuvo tu suposición',
    'howToPlay.rule4': 'Usa la retroalimentación para hacer mejores suposiciones',
    'howToPlay.tileColors': 'Colores de las Fichas',
    'howToPlay.green': 'La letra está en la palabra y en la posición correcta',
    'howToPlay.yellow': 'La letra está en la palabra pero en la posición incorrecta',
    'howToPlay.gray': 'La letra no está en la palabra',
    'howToPlay.tips': 'Consejos Pro',
    'howToPlay.tip1.title': 'Comienza con Letras Comunes',
    'howToPlay.tip1.desc': 'Comienza con palabras que contengan vocales y consonantes comunes como A, E, I, O, U, R, S, T, L, N.',
    'howToPlay.tip2.title': 'Usa Eliminación por Proceso',
    'howToPlay.tip2.desc': 'Presta atención a las letras grises - no están en la palabra. Evita usarlas en futuras suposiciones.',
    'howToPlay.tip3.title': 'La Posición Importa',
    'howToPlay.tip3.desc': 'Las letras amarillas están en la palabra pero en posición incorrecta. Pruébalas en diferentes lugares.',
    'howToPlay.tip4.title': 'Piensa Estratégicamente',
    'howToPlay.tip4.desc': 'Cada suposición debería darte la máxima información sobre posiciones y presencia de letras.',
    'howToPlay.what': '¿Qué es Wordless?',
    'howToPlay.whatDesc1': 'Wordless está inspirado en el formato popular de juegos de rompecabezas de palabras pero ofrece características únicas como longitudes variables de palabras y desafíos diarios.',
    'howToPlay.whatDesc2': 'Perfecto para entusiastas de juegos de palabras que quieren desafiarse con rompecabezas de diferentes niveles de dificultad.',
    'howToPlay.faq': 'Preguntas Frecuentes',
    'howToPlay.faq1.q': '¿Puedo jugar rompecabezas anteriores?',
    'howToPlay.faq1.a': 'Cada día presenta un rompecabezas único. Puedes cambiar las longitudes de palabras para obtener diferentes desafíos.',
    'howToPlay.faq2.q': '¿Qué longitudes de palabras están disponibles?',
    'howToPlay.faq2.a': 'Puedes jugar con palabras de 3 a 8 letras, cada una ofreciendo diferentes niveles de dificultad.',
    'howToPlay.faq3.q': '¿Hay pistas disponibles?',
    'howToPlay.faq3.a': 'El juego proporciona retroalimentación codificada por colores después de cada suposición - ¡ese es tu sistema de pistas!',
    'howToPlay.faq4.q': '¿Puedo jugar sin conexión?',
    'howToPlay.faq4.a': '¡Sí! Una vez cargado, puedes jugar el rompecabezas actual sin conexión a internet.',
  },
  it: {
    'header.title': 'Wordless',
    'header.subtitle': 'Sfida la tua mente con enigmi di parole',
    'header.letsPlay': 'Giochiamo!',
    'header.learnMore': 'Scopri di Più',
    'game.confirmChange': 'Sei sicuro di voler cambiare la lunghezza della parola? Questo resetterà il tuo gioco attuale.',
    'game.wordLengthUpdated': 'Lunghezza parola aggiornata a {{length}} lettere',
    'game.newWordGenerated': 'È stata generata una nuova parola',
    'game.congratulations': 'Congratulazioni!',
    'game.solved': 'Hai risolto l\'enigma!',
    'game.gameOver': 'Gioco Finito',
    'game.wordWas': 'La parola era: {{word}}',
    'game.wordTooShort': 'Parola troppo corta',
    'game.enterWord': 'Per favore inserisci una parola di {{length}} lettere',
    'game.confirmReset': 'Sei sicuro di voler resettare il gioco?',
    'game.loading': 'Caricamento nuovo enigma...',
    'game.dailyChallenge': 'Sfida Quotidiana delle Parole',
    'game.newPuzzle': 'Un nuovo enigma ogni giorno!',
    'game.youWon': 'Hai Vinto!',
    'game.betterLuck': 'Più Fortuna la Prossima Volta!',
    'game.solvedIn': 'L\'hai risolto in {{count}} tentativi!',
    'game.tryDifferent': 'Prova una lunghezza di parola diversa per una nuova sfida.',
    'game.playAgain': 'Gioca Ancora',
    'game.try': 'Prova {{length}} Lettere',
    'about.title': 'Riguardo a Wordless',
    'about.description1': 'Wordless è un gioco di enigmi di parole stimolante che mette alla prova il tuo vocabolario e le tue abilità di deduzione.',
    'about.description2': 'Ogni giorno porta un nuovo enigma con parole di lunghezze variabili da 3 a 8 lettere.',
    'about.description3': 'Usa il feedback codificato a colori per restringere la parola corretta in 6 tentativi.',
    'about.description4': 'Sfidati con diverse lunghezze di parole e migliora le tue abilità di risoluzione delle parole!',
    'howToPlay.title': 'Come Giocare',
    'howToPlay.gameRules': 'Regole del Gioco',
    'howToPlay.rule1': 'Indovina la parola nascosta in 6 tentativi o meno',
    'howToPlay.rule2': 'Ogni ipotesi deve essere una parola valida della lunghezza corretta',
    'howToPlay.rule3': 'Dopo ogni ipotesi, i colori delle tessere cambieranno per mostrare quanto era vicina la tua ipotesi',
    'howToPlay.rule4': 'Usa il feedback per fare ipotesi migliori',
    'howToPlay.tileColors': 'Colori delle Tessere',
    'howToPlay.green': 'La lettera è nella parola e nella posizione corretta',
    'howToPlay.yellow': 'La lettera è nella parola ma nella posizione sbagliata',
    'howToPlay.gray': 'La lettera non è nella parola',
    'howToPlay.tips': 'Consigli Pro',
    'howToPlay.tip1.title': 'Inizia con Lettere Comuni',
    'howToPlay.tip1.desc': 'Inizia con parole contenenti vocali e consonanti comuni come A, E, I, O, U, R, S, T, L, N.',
    'howToPlay.tip2.title': 'Usa l\'Eliminazione per Processo',
    'howToPlay.tip2.desc': 'Fai attenzione alle lettere grigie - non sono nella parola. Evita di usarle nelle ipotesi future.',
    'howToPlay.tip3.title': 'La Posizione Conta',
    'howToPlay.tip3.desc': 'Le lettere gialle sono nella parola ma nella posizione sbagliata. Provali in posti diversi.',
    'howToPlay.tip4.title': 'Pensa Strategicamente',
    'howToPlay.tip4.desc': 'Ogni ipotesi dovrebbe darti il massimo delle informazioni su posizioni e presenza delle lettere.',
    'howToPlay.what': 'Cos\'è Wordless?',
    'howToPlay.whatDesc1': 'Wordless è ispirato al popolare formato di giochi di enigmi di parole ma offre caratteristiche uniche come lunghezze variabili delle parole e sfide quotidiane.',
    'howToPlay.whatDesc2': 'Perfetto per gli appassionati di giochi di parole che vogliono sfidarsi con enigmi di diversi livelli di difficoltà.',
    'howToPlay.faq': 'Domande Frequenti',
    'howToPlay.faq1.q': 'Posso giocare enigmi precedenti?',
    'howToPlay.faq1.a': 'Ogni giorno presenta un enigma unico. Puoi cambiare le lunghezze delle parole per ottenere sfide diverse.',
    'howToPlay.faq2.q': 'Quali lunghezze di parole sono disponibili?',
    'howToPlay.faq2.a': 'Puoi giocare con parole da 3 a 8 lettere, ognuna offre diversi livelli di difficoltà.',
    'howToPlay.faq3.q': 'Ci sono suggerimenti disponibili?',
    'howToPlay.faq3.a': 'Il gioco fornisce feedback codificato a colori dopo ogni ipotesi - questo è il tuo sistema di suggerimenti!',
    'howToPlay.faq4.q': 'Posso giocare offline?',
    'howToPlay.faq4.a': 'Sì! Una volta caricato, puoi giocare l\'enigma attuale senza una connessione internet.',
  },
  tr: {
    'header.title': 'Wordless',
    'header.subtitle': 'Kelime bulmacalarıyla zihninizi zorlayın',
    'header.letsPlay': 'Hadi Oynayalım!',
    'header.learnMore': 'Daha Fazla Öğren',
    'game.confirmChange': 'Kelime uzunluğunu değiştirmek istediğinizden emin misiniz? Bu mevcut oyununuzu sıfırlayacak.',
    'game.wordLengthUpdated': 'Kelime uzunluğu {{length}} harfe güncellendi',
    'game.newWordGenerated': 'Yeni bir kelime oluşturuldu',
    'game.congratulations': 'Tebrikler!',
    'game.solved': 'Bulmacayı çözdünüz!',
    'game.gameOver': 'Oyun Bitti',
    'game.wordWas': 'Kelime şuydu: {{word}}',
    'game.wordTooShort': 'Kelime çok kısa',
    'game.enterWord': 'Lütfen {{length}} harfli bir kelime girin',
    'game.confirmReset': 'Oyunu sıfırlamak istediğinizden emin misiniz?',
    'game.loading': 'Yeni bulmaca yükleniyor...',
    'game.dailyChallenge': 'Günlük Kelime Meydan Okuması',
    'game.newPuzzle': 'Her gün yeni bir bulmaca!',
    'game.youWon': 'Kazandınız!',
    'game.betterLuck': 'Bir Dahaki Sefere Daha İyi Şans!',
    'game.solvedIn': '{{count}} tahminde çözdünüz!',
    'game.tryDifferent': 'Yeni bir meydan okuma için farklı kelime uzunluğu deneyin.',
    'game.playAgain': 'Tekrar Oyna',
    'game.try': '{{length}} Harf Dene',
    'about.title': 'Wordless Hakkında',
    'about.description1': 'Wordless, kelime dağarcığınızı ve çıkarım becerilerinizi test eden zorlu bir kelime bulmaca oyunudur.',
    'about.description2': 'Her gün 3 ila 8 harf arasında değişen uzunluklarda yeni bir bulmaca getiriyor.',
    'about.description3': 'Doğru kelimeyi 6 denemede daraltmak için renk kodlu geri bildirimi kullanın.',
    'about.description4': 'Farklı kelime uzunluklarıyla kendinizi zorlayın ve kelime çözme becerilerinizi geliştirin!',
    'howToPlay.title': 'Nasıl Oynanır',
    'howToPlay.gameRules': 'Oyun Kuralları',
    'howToPlay.rule1': 'Gizli kelimeyi 6 denemede veya daha azında tahmin edin',
    'howToPlay.rule2': 'Her tahmin doğru uzunlukta geçerli bir kelime olmalı',
    'howToPlay.rule3': 'Her tahminden sonra, karo renkleri tahmininizin ne kadar yakın olduğunu göstermek için değişecek',
    'howToPlay.rule4': 'Daha iyi tahminler yapmak için geri bildirimi kullanın',
    'howToPlay.tileColors': 'Karo Renkleri',
    'howToPlay.green': 'Harf kelimede var ve doğru konumda',
    'howToPlay.yellow': 'Harf kelimede var ama yanlış konumda',
    'howToPlay.gray': 'Harf kelimede yok',
    'howToPlay.tips': 'Pro İpuçları',
    'howToPlay.tip1.title': 'Yaygın Harflerle Başlayın',
    'howToPlay.tip1.desc': 'A, E, I, O, U, R, S, T, L, N gibi yaygın sesli ve sessiz harfleri içeren kelimelerle başlayın.',
    'howToPlay.tip2.title': 'Eleme Yöntemini Kullanın',
    'howToPlay.tip2.desc': 'Gri harflere dikkat edin - kelimede yoklar. Gelecekteki tahminlerde bunları kullanmaktan kaçının.',
    'howToPlay.tip3.title': 'Konum Önemli',
    'howToPlay.tip3.desc': 'Sarı harfler kelimede var ama yanlış konumda. Onları farklı yerlerde deneyin.',
    'howToPlay.tip4.title': 'Stratejik Düşünün',
    'howToPlay.tip4.desc': 'Her tahmin size harf konumları ve varlığı hakkında maksimum bilgi vermeli.',
    'howToPlay.what': 'Wordless Nedir?',
    'howToPlay.whatDesc1': 'Wordless popüler kelime bulmaca oyunu formatından ilham alır ancak değişken kelime uzunlukları ve günlük meydan okumalar gibi benzersiz özellikler sunar.',
    'howToPlay.whatDesc2': 'Farklı zorluk seviyelerinde bulmacalarla kendilerini zorlamak isteyen kelime oyunu tutkunları için mükemmel.',
    'howToPlay.faq': 'Sık Sorulan Sorular',
    'howToPlay.faq1.q': 'Önceki bulmacaları oynayabilir miyim?',
    'howToPlay.faq1.a': 'Her gün benzersiz bir bulmaca sunuyor. Farklı zorluklar için kelime uzunluklarını değiştirebilirsiniz.',
    'howToPlay.faq2.q': 'Hangi kelime uzunlukları mevcut?',
    'howToPlay.faq2.a': '3 ila 8 harf uzunluğunda kelimelerle oynayabilirsiniz, her biri farklı zorluk seviyeleri sunuyor.',
    'howToPlay.faq3.q': 'İpucu mevcut mu?',
    'howToPlay.faq3.a': 'Oyun her tahminden sonra renk kodlu geri bildirim sağlıyor - bu sizin ipucu sisteminiz!',
    'howToPlay.faq4.q': 'Çevrimdışı oynayabilir miyim?',
    'howToPlay.faq4.a': 'Evet! Yüklendikten sonra mevcut bulmacayı internet bağlantısı olmadan oynayabilirsiniz.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.split('-')[0];
  const supportedLangs: Language[] = ['en', 'fr', 'es', 'it', 'tr'];
  return supportedLangs.includes(browserLang as Language) ? (browserLang as Language) : 'en';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('wordless-language');
    if (saved && ['en', 'fr', 'es', 'it', 'tr'].includes(saved)) {
      return saved as Language;
    }
    return detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem('wordless-language', language);
  }, [language]);

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    if (variables) {
      Object.entries(variables).forEach(([varKey, varValue]) => {
        translation = translation.replace(`{{${varKey}}}`, String(varValue));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
