// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrclywumuxaahusncomp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyY2x5d3VtdXhhYWh1c25jb21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTgzNTIsImV4cCI6MjA1OTQ5NDM1Mn0.VI6toXW7Ky6o4-cuH-tFI7yb0F5CrEq4zCTi3FFMwj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);